### ISSUE TITLE
画像加工系

### ISSUE THREAD

**Issue by ryutah** [ryutah/trash-training-camp#5]
ref #1 

# システム構成案
## 顔認識など
* OpenCV使う？
  - 顔認識とかできるやつ。
  - なんか加工とかもできる？使ったことないから実はよくわからない。
* VisionAPI
  - 実はあんまり精度高くないとかなんとか。
  - クラウドだからお手軽感はあるかも

## 画像加工の流れ
1. 写真取る
2. クラウドストレージサービス系にアップロード
  (ここの手動感がぶっちゃけダサいからなんとかできないか考えたい。)
3. ストリーム処理で、画像処理
4. SlackBotとかで、加工終了した画像を投稿できたらいいよね。

## その他
画像加工系はぶっちゃけよくわからない。
興味ある人が調査してくれるとありがたい。

**Comment by yoshioH** [comment]
FaaSに向けて
GET /画像加工/ホワイトニング/Base64
みたいなことできないもんかね。ちょっと調べてみる。

**Comment by ryutah** [comment]
> 1. 写真取る
> 2. クラウドストレージサービス系にアップロード
> (ここの手動感がぶっちゃけダサいからなんとかできないか考えたい。)


ココらへんとかも、全部SlackBotでいい気がしてきた。

```
画像変換チャンネル的なの作って、BotをInvaite
↓
チャンネルにSlackに画像アップロード
↓
画像アップロードをフックして（多分できるでしょ）処理開始
↓
画像加工（画像処理クラウドサービス？自力加工？）
↓
同チャンネルに加工後の画像アップロード
```

みたいな感じ。
Slackのファイル添付で、直接写メも取れるしそこそこ使いやすいと思う。

気が向いたときにシステム構成図でも書く（かも）

**Comment by yoshioH** [comment]
画像処理についてちょっと調べたり、考えたりしてみた。

顔のホワイトニングの機能を分解すると、
1. 顔を輪郭線や面で認識する機能
2. 肌を判定する機能
3. 肌の色（色相・彩度・明度）を取得する機能
4. 1,2,3の積集合に対してホワイトニングする機能

になるのかな？
1はOpenCVに機能ありそうだし、4の色の調整はがんばればできそうな気がするけど、2,3に関してはどういう方法があるんだろ？特徴量がない部分を抽出するってのはかなりエグい気がする。鼻を抽出して代用するって回避方法はイケるか？

次に顔の画像に黒目線やスタンプを入れる機能。これを分解するとこんな感じだと思う。
1. 顔の各パーツの座標を取得する機能
2. 顔の各パーツ間の距離などから顔の大きさを判定する機能
3. 顔の各パーツの座標に黒目線やスタンプを拡大してのっける機能

1は[VisionAPI](https://cloud.google.com/vision/docs/reference/rest/v1/images/annotate#Landmark)とか[detactFace();](http://detectface.com/)使えばできそう。2は機械学習とかで適切な値を割り出してあげられるとイケてるんだろうけど、テキトーな定数使って誤魔化せそうでもある。3の画像のオーバレイはそれこそググればたくさん情報出てきそう。つーか似ていることを[やってる人がもういるね](https://qiita.com/k_sui_14/items/5386db1a118103b1828f)。

**Comment by ryutah** [comment]
> 肌を判定する機能
> 肌の色（色相・彩度・明度）を取得する機能

OpenCVだとこんなんできるみたいですね。
http://d.hatena.ne.jp/mintsu123/20111123/1322065624

もしくは、適当に手打ちで肌色判定する色調とか決めちゃうとか？
特定の人しかホワイトニングされないとかなりそうだけどそれはそれで面白い気がする。


> 1,2,3の積集合に対してホワイトニングする機能

調整なんかせんで、固定色で鈴木その子なみに真っ白にしたったらええんちゃうん？（適当）

> 顔の各パーツの座標を取得する機能

OpenCVにも顔パーツ判定してるサンプルありますね。これは結構どうにかなりそう。
https://qiita.com/hitomatagi/items/04b1b26c1bc2e8081427


> 顔の各パーツ間の距離などから顔の大きさを判定する機能
> 顔の各パーツの座標に黒目線やスタンプを拡大してのっける機能

顔のサイズなんかは、画像処理系のライブラリとかAPIで勝手に判定してくれないですかね？
顔を矩形で囲むサンプルとかはよく見るんで、そのくらいは取得できそうな気がします。
判定してくれるならそれそのまま使ってオーバーレイ系の画像拡大縮小すれば良さそう。

**Comment by yoshioH** [comment]
> 調整なんかせんで、固定色で鈴木その子なみに真っ白にしたったらええんちゃうん？（適当）

オプションで樽美酒研二も追加しよーぜ。

**Comment by ryutah** [comment]
とりあえず今回はやらないのでクローズ
