### ISSUE TITLE
AAを画像化するAPI

### ISSUE THREAD

**Issue by ryutah** [ryutah/trash-training-camp#7]
ref #1 
主にSlackでAAを使いたいという全国1億人のニーズを満たすために作る。

手順としてはこんな感じ。

SlackでSlash Commandで画像化したいAAを送信
↓
変換サーバが文字列受信
↓
画像生成
↓
Slackに投稿

* 画像生成は[ImageMagick](http://blog.penlabo.net/archives/2695)とか使えばできそう感。
* AAのを快適に見るための環境には、`16px（12pt）のＭＳ Ｐゴシック、行間2px`で描画する必要があるらしい([参考](http://tail.s170.xrea.com/html/text/aa_promo/aa_setting/))
* MS Pゴシックをサーバで使うのは厳しいので代替フォントを使う
  - [IPAモナーフォント](https://sites.google.com/site/tetsuroweb/home/software/ubuntu/applications/fonts/ipamonafonts)
  - 他にも探せばありそう
* 画像生成APIはDockerでさくっと作ろう

**Comment by yoshioH** [comment]
slash commandはよくわからないんだけど、optionみたいなの入れられるの？
例えば、`/command probrem?` って入れたら https://rr.img.naver.jp/mig?src=http%3A%2F%2Fcdn.jaxov.com%2Fwp-content%2Fuploads%2F2012%2F02%2FTrollface-Meme-Face.jpg&twidth=1000&theight=0&qlt=80&res_format=jpg&op=r が返ってくるショートカットみたいなオプションがあっても面白そう。

**Comment by ryutah** [comment]
とりあえず今回はやらないのでクローズ
