### ISSUE TITLE
クローラー開発調査

### ISSUE THREAD

**Issue by ryutah** [ryutah/trash-training-camp#8]
ref #4 

クローラー実装のための調査を行う
* サンプルコード
* GAEの利用を想定

**Comment by yoshioH** [comment]
自分自身、クローラについて勘違いしていたので、とりあえず言葉の定義からしようと思う。

- クローラ
    Webページの内容をダウンロードして収集、ページ内のリンクをたどる
- スクレイピング
    
- Webスクレイピング

全体として実現したいことはクローラというよりもWebスクレイピング

**Comment by yoshioH** [comment]
誤操作でクローズしてしまったので再オープン。

**Comment by yoshioH** [comment]
まず、クローラの言葉の定義から
- スクレイピング
    Webサイトから必要な情報を抽出する
- クローリング
    スクレイピングをするための手段。ページ内のリンクを辿り、Webサイトを閲覧するような動きをする

過去に攻撃と見なされた例もある。こちらは良識的なアクセス頻度だと思ったとしても、相手によっては攻撃と認識しているかもしれない。
https://ja.wikipedia.org/wiki/%E5%B2%A1%E5%B4%8E%E5%B8%82%E7%AB%8B%E4%B8%AD%E5%A4%AE%E5%9B%B3%E6%9B%B8%E9%A4%A8%E4%BA%8B%E4%BB%B6
http://takagi-hiromitsu.jp/diary/20130316.html
https://qiita.com/nezuq/items/c5e827e1827e7cb29011
https://qiita.com/nezuq/items/3cc9772118ad112c18dc

**Comment by ryutah** [comment]
> 過去に攻撃と見なされた例もある。こちらは良識的なアクセス頻度だと思ったとしても、相手によっては攻撃と認識しているかもしれない。

`robots.txt` 守っとけばとりあえず大丈夫じゃないかなーと…
ココらへんのことをガチガチに考えすぎるとどんどん手が進まなくなると思うので、一旦頭のすみに入れとくくらいにしておきたいです。

商用利用するわけでもないので攻撃認定されてブロックされてもぶっちゃけ痛くも痒くも無いですから、とりあえずやってみて色々課題とか見つけるくらいで良いかと。

**Comment by yoshioH** [comment]
まぁ、その通りなんだけどね。
オープンな場所だし、公共の福祉は守りまっせ宣言みたいなもんす。

**Comment by yoshioH** [comment]
ちょぼちょぼ調べたり、試したりして思ったこと。
- 1サイト1秒のルールを守ると計算機がヒマになるし時間もかかるので並列化しないとつらい
- [こんな感じで](http://ja.uncyclopedia.info/wiki/%E3%81%9F%E3%82%89%E3%81%84%E5%9B%9E%E3%81%97)ループするサイトへの対策としてアクセス履歴のキャッシュが必要
- Wikipediaみたいにリンクだらけのページは自然言語解析とかキャッシュが必要になる（今回は不要）

リンクだらけのページへの対策とか、目的にはそぐわないから回避できそうなものもある。
Pythonだと気軽に試せて楽しいのでもう少し調べたり試したりしてみる。

**Comment by yoshioH** [comment]
GAEに載せる方法は[Flask使ったクイックスタート](https://cloud.google.com/python/getting-started/hello-world?hl=ja)あるしFlaskでいいかなぁーって甘いこと考えてる。

**Comment by ryutah** [comment]
> 1サイト1秒のルールを守ると計算機がヒマになるし時間もかかるので並列化しないとつらい

[Taskqueue](https://cloud.google.com/appengine/docs/standard/python/taskqueue/)とか使って並列化したほうがいいよなーとは思ってました。
自力でスレッド作ったりして並列化するのは地獄しか見えないんで、クラウド的なアプローチで並列化させたいところ。

>こんな感じでループするサイトへの対策としてアクセス履歴のキャッシュが必要

あーそういうサイト対策はちゃんと考えてなかったですねー。
GAEなら[Memcache](https://cloud.google.com/appengine/docs/standard/python/memcache/using?hl=ja)とか使って直近にアクセスしたサイト保持しとくとかになりそうですかね。

> Wikipediaみたいにリンクだらけのページは自然言語解析とかキャッシュが必要になる（今回は不要）

自然言語処理が必要になる理由がいまいちピンとこない…？

> GAEに載せる方法はFlask使ったクイックスタートあるしFlaskでいいかなぁーって甘いこと考えてる。

フレキシブル環境は**お金的にとてもつらい**のでやるならスタンダート環境になるかと。
（というか、まだフレキシブル環境はいろいろと使いづらいところが多い…）
スタンダート環境だと[このクイックスタート](https://cloud.google.com/appengine/docs/standard/python/quickstart)ですね。
Webアプリ的な機能はほぼ必要ないはずなんで、とりあえずリクエスト受信できるエンドポイント用意できりゃFWは特にこだわらなくていい気がします。
公式のチュートリアルに乗ってるヤツ使っときゃええやろて感じですね。

**Comment by yoshioH** [comment]
そういえば、スタンダート環境でって話したね。フォローありがと :-)

> 自然言語処理が必要になる理由がいまいちピンとこない…？

実際はWikipediaみたいに由緒正しいハイパーテキストじゃないと問題にならないと思うけどね。
例えば、Wikipediaで
　アメリカ航空宇宙局 -> スプートニクス -> コンスタンチン・ツィオルコフスキー
って辿るシナリオを想定して実際にアメリカ航空宇宙局のHTMLソースを見ると、リンク祭りで絶望するやん？片っ端からリンクするのも手だとは思うんだけど、計算機リソースが有限だったり時間がかかる処理の場合は効率的にリンクを取捨選択する手法を使わざるを得なくなってくる。ってなると、自然言語処理は選択肢の一つになってきてしまう。

今回は汎用的に作る必要がないし、そんな人間的な指向性を持った検索もしないから不要な機能。（だけど、調べてると楽しい）

**Comment by ryutah** [comment]
自然言語処理 + 機械学習的な仕組み必要そうなケースですねー。
[word2vec](https://qiita.com/To_Murakami/items/cc225e7c9cd9c0ab641e)とかで類義語推測的なのを差し込んで上げると、頭いい感じになってくれそうな気がする。

**Comment by yoshioH** [comment]
GAEの雛形も作ってもらったし、ググることとrobot.txtを読み込むことはできたんで、一旦クローズ。
もう少し詳しい実装は開発レポジトリのISSUEにする。
(https://github.com/yoshioH/pystudy)
